### ISSUE TITLE
Fix google chrome version detection for MacOS

### ISSUE THREAD

**Issue by giggio** [testimio/chrome-version#1]
Please see: https://github.com/giggio/node-chromedriver/pull/248

**Comment by benjamingr** [comment]
@eladrkatz can you please spend an hour or two looking at this today?

**Comment by eladrkatz** [comment]
@giggio @benjamingr fix has been issued and published. thanks!

**Comment by benjamingr** [comment]
Thanks for the quick fix ❤️
