### ISSUE TITLE
Version returned has new line on string

### ISSUE THREAD

**Issue by HughePaul** [testimio/chrome-version#10]
The version returned to me has a newline at the end of the string.

This is breaking the install script on npm `chromedriver` as it fails a regular expression that tries to remove the patch number.

## versions
Chrome: 97.0.4692.99
Node.js: v12.18.4
OS: Linux ubuntu 18.04.2

## Reproduction
```
node
Welcome to Node.js v12.18.4.
Type ".help" for more information.
> const { getChromeVersion } = require('@testim/chrome-version');
undefined
> getChromeVersion().then(v => console.log(JSON.stringify(v)));
Promise { <pending> }
> "97.0.4692.99\n"
```

**Comment by benjamingr** [comment]
As a workaround you can downgrade the version of crhomedriver before the last updates to support Chromium

**Comment by Linkgoron** [comment]
I've released version 1.1.2 to remove the newline and fix the issue

**Comment by HughePaul** [comment]
this version of chrome appears to be returning a space on the end which seems to be the cause of the replace regex not matching
```
echo "'$(google-chrome --version)'"
'Google Chrome 97.0.4692.99 '
```
--

thanks i'll give that a go, and raise a chromedriver issue/pr

**Comment by Linkgoron** [comment]
> this version of chrome appears to be returning a space on the end which seems to be the cause of the replace regex not matching
> 
> ```
> echo "'$(google-chrome --version)'"
> 'Google Chrome 97.0.4692.99 '
> ```
> 
> --
> 
> thanks i'll give that a go, and raise a chromedriver issue/pr

Thanks for checking that out. I can assume that the issue was fixed after reinstalling chromedriver?

**Comment by HughePaul** [comment]
Yes that's working and has brought in the new version.

Thanks
