### ISSUE TITLE
Chromium wrongly detected in Node.js Docker image

### ISSUE THREAD

**Issue by slhck** [testimio/chrome-version#14]
Given the following Dockerfile:

```Dockerfile
FROM node:18-bullseye

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -qq \
  && apt-get install -y \
  chromium \
  && apt-get clean -y && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/*
```

Then:

```
docker build -t tmp .
```

When I drop into the container:

```
docker run --rm -it tmp /bin/bash
```

… and run:

```
$ npm i @testim/chrome-version

added 1 package, and audited 2 packages in 388ms

found 0 vulnerabilities
$ node
Welcome to Node.js v18.9.0.
Type ".help" for more information.
>     const { getChromeVersion } = require('@testim/chrome-version');
undefined
> 
> getChromeVersion(true).then((c) => console.log(c));
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 274,
  [Symbol(trigger_async_id_symbol)]: 258
}
> 11.5
```

You see it returns 11.5 which seems to actually be the Debian version, not Chromium.

**Comment by benjamingr** [comment]
@MoLow who is maintaining this now?

**Comment by Linkgoron** [comment]
Hi Benji,

Dror will handle it.

Regards,

Omri
________________________________

**Comment by drore** [comment]
Fixed the extraction regex

**Comment by slhck** [comment]
Thanks for the quick fix! If you could make a release, that would be nice, since [this package](https://www.npmjs.com/package/chromedriver) is also impacted.

**Comment by drore** [comment]
Sure

**Comment by drore** [comment]
> Thanks for the quick fix! If you could make a release, that would be nice, since [this package](https://www.npmjs.com/package/chromedriver) is also impacted.

Fix publised
